### PR TITLE
Add autosync action

### PR DESCRIPTION
**Pull request by artyom-morozov**
Automatically sync SolaceLabs commits to SolaceDev

### CODE REVIEW

**Review by shooshmand-sol — APPROVED** [review]
👍 looks great.

**Review by johnvincentcorpuz — APPROVED** [review]
👍

**Review by AmanRiat1 — COMMENTED** [review]
does the workflow have the right permissions to execute this?

**Review by AmanRiat1 — APPROVED** [review]
ignore my last comment I see we're using a specific GH_PAT. Looks good!

**Pull request merged**
